[package]
name = "kyaaa"
version = "0.1.3"
edition = "2024"
description="Zero heap. Zero vtables. A static no_std heterogeneous list (HList) that murders dynamic dispatch and melts straight into raw ASM... kyaaa!"
keywords = ["hlist", "no_std", "zero-cost", "macro", "data-structures"]
categories = ["data-structures", "no-std", "embedded", "memory-management"]
license = "AGPL-3.0-only"
repository = "https://github.com/SAP2B/kyaaa"
readme = "README.md"

[dependencies]

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
panic = "abort"
lto = true
codegen-units = 1
strip = true


[[bench]]
name = "webserver"
path = "benches/webserver.rs"
harness = false
